---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create app directory in server"
  file:
    path: ~/app
    state: directory

- name: "Copy artifact to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: ~/app/artifact.tar.gz

- name: "Extract and deploy artifact"
  shell: |
    cd ~/app
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm install
    npm audit fix && npm run build
    cd dist
    pm2 start npm --name backend -- start
