---
- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Create app backend directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "install dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm install
    npm audit fix && npm run build
    cd dist
    pm2 start npm --name backend -- start
