---
- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: ~

- name: "Create app backend directory"
  file:
    path: ~/backend
    state: directory

- name: "install dependencies"
  shell: |
    cd ~
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm install
    npm audit fix && npm run build
    cd dist
    pm2 start npm -- start
